name: "My action"
description: "Mi primer action"

inputs:
  message: "MEssage to print"
  required: true
  default: "Hola"

runs:
  using: "composite"

  steps:
    - name: Hola mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash